#!/usr/bin/env bash

# Note that HTTPie does not add line endings, so use 'echo'

# Better debugging output when using `bash -x <script>`
export PS4='+${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]:+${FUNCNAME[0]}():} '

# Enable good runtime checks by Bash when executing the script
set -e
set -u
set -o pipefail

function print-usage() {
    cat <<EOU
Usage: $0 [-d|--debug][-h|--help][-s|--server]
EOU
}

function print-help() {
    print-usage
    cat <<EOH

Options:
  -d, --debug   Trace this script
  -h, --help    Print help and exit normally
  -s, --server  Run server in background for duration of script.
                Default is to run against an existing local server instance.
EOH
}

function get-health-status() {
    curl -s -o /dev/null -w '%{http_code}\n' \
        http://localhost:8080/admin/health
}

function shutdown-server {
    local status=$?
    local server_pid="$1"

    http POST :8080/admin/shutdown
    wait "$server_pid" 2>/dev/null || true
    exit "$status"
}

function run-server() {
    ./mvnw -q spring-boot:run \
        -Dspring-boot.run.arguments=--logging.level.root=ERROR &
    local server_pid=$!

    for n in {1..10}
    do
        sleep 1
        http_code="$(get-health-status)" || true
        case "$http_code" in
        000 ) echo "$0: Health check #$n..." ;;  # Still waiting or died
        200 )
            # shellcheck disable=SC2064
            trap "shutdown-server $server_pid" EXIT
            return
            ;;
        * )
            echo "$0: Health error: expected 200; got $http_code" >&2
            exit 1
            ;;
        esac
    done

    # See if server is even running
    if lsof -i :8080
    then
        echo "$0: Server not responding on 8080" >&2
        exit 1
    else
        echo "$0: Server not listening on 8080" >&2
        exit 1
    fi
}

debug=false
server=false
while getopts :dhs-: opt; do
    # Complex, but addresses "--foo=bar" type options
    [[ $opt == - ]] && opt=${OPTARG%%=*} OPTARG=${OPTARG#*=}
    case $opt in
    d | debug) debug=true ;;
    h | help)
        print-help
        exit 0
        ;;
    s | server) server=true ;;
    *)
        print-usage >&2
        exit 2
        ;;
    esac
done
shift $((OPTIND - 1))

$debug && set -x

$server && run-server

: <<'EOC'
# Output should look like:

== REST
(See also http://localhost:8080/rest in a browser)
http://localhost:8080/rest/books/book-1
{"id":"book-1","isbn":"978-1-408855-652","authorId":"author-1","title":"Harry Potter and the Philosopher's Stone","pages":223,"moby":true}

== REST WITH PAGING (results vary if there are writes between reads)
(See also http://localhost:8080/rest in a browser)
* Page #1:
http://localhost:8080/rest/books?page=1&size=1&sort=title,asc
[{"id":"book-1","isbn":"978-1-408855-652","authorId":"author-1","title":"Harry Potter and the Philosopher's Stone","pages":223,"moby":true}]

* Page #2:
http://localhost:8080/rest/books?page=2&size=1&sort=title,asc
[{"id":"book-3","isbn":"978-0-345337-665","authorId":"author-3","title":"Interview with the vampire","pages":371,"moby":false}]

== HATEOAS
(See also http://localhost:8080/data in a browser)
http://localhost:8080/data/books/book-1
{
  "isbn" : "978-1-408855-652",
  "authorId" : "author-1",
  "title" : "Harry Potter and the Philosopher's Stone",
  "pages" : 223,
  "moby" : true,
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/data/books/book-1"
    },
    "book" : {
      "href" : "http://localhost:8080/data/books/book-1"
    }
  }
}

== GRAPHQL
(See also http://localhost:8080/graphiql in a browser)
http://localhost:8080/graphql query='<...>'
{"data":{"bookByID":{"id":"book-1","isbn":"978-1-408855-652","title":"Harry Potter and the Philosopher's Stone","pages":223,"moby":true,"author":{"id":"author-1","firstName":"Joanne","lastName":"Rowling"}}}}

== GRAPHQL SCHEMA
(See also http://localhost:8080/graphiql in a browser)
http://localhost:8080/graphql/schema
"Marks the field, argument, input field or enum value as deprecated"
directive @deprecated(
    "The reason for the deprecation"
    reason: String = "No longer supported"
  ) on FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM_VALUE | INPUT_FIELD_DEFINITION

"Directs the executor to include this field or fragment only when the `if` argument is true"
directive @include(
    "Included when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Indicates an Input Object is a OneOf Input Object."
directive @oneOf on INPUT_OBJECT

"Directs the executor to skip this field or fragment when the `if` argument is true."
directive @skip(
    "Skipped when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Exposes a URL that specifies the behaviour of this scalar."
directive @specifiedBy(
    "The URL that specifies the behaviour of this scalar."
    url: String!
  ) on SCALAR

"Books do not write themselves, you know."
type Author {
  "TODO: A first/last name pair assumes cultural conventions."
  firstName: String
  id: ID!
  lastName: String
}

"Read more books."
type Book {
  "TODO: Should be a plural, not a singular."
  author: Author
  id: ID!
  isbn: String
  moby: Boolean
  pages: Int
  title: String
}

"TODO: Support Dewey Decimal and others."
type Query {
  " A comment that should be ignored by documentation tools"
  bookByID(id: ID!): Book
}

== FAILURES
(See also http://localhost:8080/data/cats/cats-are-funny-but-not-books in a browser)
This is a 404 although the message about "static resource" may be misleading.
http://localhost:8080/data/cats/cats-are-funny-but-not-books
{"timestamp":"2025-04-30T18:33:03.845+00:00","status":404,"error":"Not Found","message":"No endpoint GET /data/cats/cats-are-funny-but-not-books.","path":"/data/cats/cats-are-funny-but-not-books"}

== DEVELOPER DOCS
Swagger UI (open this in a browser not the command line):
http://localhost:8080/rest

* Demo OpenAPI spec as JSON:
http://localhost:8080/openapi

* Demo OpenAPI spec as YAML:
http://localhost:8080/openapi.yaml
EOC

cat <<'EOM'
== REST
(See also http://localhost:8080/rest in a browser)
http://localhost:8080/rest/books/book-1
EOM
http :8080/rest/books/book-1
echo

cat <<'EOM'

== REST WITH PAGING (results vary if there are writes between reads)
(See also http://localhost:8080/rest in a browser)
* Page #1:
http://localhost:8080/rest/books?page=1&size=1&sort=title,asc
EOM
http ':8080/rest/books?page=1&size=1&sort=title,asc'
echo
cat <<'EOM'

* Page #2:
http://localhost:8080/rest/books?page=2&size=1&sort=title,asc
EOM
http ':8080/rest/books?page=2&size=1&sort=title,asc'
echo

cat <<'EOM'

== HATEOAS
(See also http://localhost:8080/data in a browser)
http://localhost:8080/data/books/book-1
EOM
http :8080/data/books/book-1
echo

cat <<'EOM'

== GRAPHQL
(See also http://localhost:8080/graphiql in a browser)
http://localhost:8080/graphql query='<...>'
EOM
http :8080/graphql query='{
  bookByID(id: "book-1") {
    id
    isbn
    title
    pages
    moby
    author {
      id
      firstName
      lastName
    }
  }
}'
echo

cat <<'EOM'

== GRAPHQL SCHEMA
(See also http://localhost:8080/graphiql in a browser)
http://localhost:8080/graphql/schema
EOM
http :8080/graphql/schema
# echo -- oddly, asking for the schema DOES add a newline at the end

cat <<'EOM'

== FAILURES
(See also http://localhost:8080/data/cats/cats-are-funny-but-not-books in a browser)
This is a 404 although the message about "static resource" may be misleading.
http://localhost:8080/data/cats/cats-are-funny-but-not-books
EOM
http :8080/data/cats/cats-are-funny-but-not-books
echo

cat <<'EOM'

== DEVELOPER DOCS
Swagger UI (open this in a browser not the command line):
http://localhost:8080/rest

* Demo OpenAPI spec as JSON:
http://localhost:8080/openapi

* Demo OpenAPI spec as YAML:
http://localhost:8080/openapi.yaml
EOM
